### ISSUE TITLE
New Pepr Set Version Script Broke IB Build Process

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#1043]
### Environment
Device and OS:
App version:
Kubernetes distro being used:
Other:

### Steps to reproduce
```bash
> node scripts/set-version.js
/app/scripts/set-version.js:13
  version = process.env.GITHUB_REF_NAME.split("");
                                        ^
TypeError: Cannot read properties of undefined (reading 'split')
    at generateVersion (/app/scripts/set-version.js:13:41)
    at Object.<anonymous> (/app/scripts/set-version.js:40:17)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49
Node.js v20.15.1
npm error code 1
npm error path /app
npm error command failed
npm error command sh -c node scripts/set-version.js
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-08-08T13_25_14_373Z-debug-0.log
subprocess exited with status 1
subprocess exited with status 1
Error: building at STEP "RUN apk add --update nodejs npm &&     npm --no-git-tag-version version ${PEPR_BUILD_VERSION} &&     npm ci &&     npm run build &&     npm cache clean --force &&     rm -fr node_modules/@types &&     rm -fr node_modules/ramda/dist &&     rm -fr node_modules/ramda/es &&     find . -name "*.ts" -type f -delete &&     mkdir node_modules/pepr && cp -r dist node_modules/pepr/dist && cp package.json node_modules/pepr/package.json": exit status 1
| Exception                    | ERROR    | Failed calling build, error: Buildah.build failed
```

### Additional Context
Add any other context or screenshots about the technical debt here.

**Comment by cmwylie19** [comment]
closing this as it was fixed in #1044
