### ISSUE TITLE
Secret - base64 decoding error around null values

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#199]
For the Pepr Zarf Agent in the Argo vertical there is an application secret that contains repo credentials that is a target for a mutation.

```bash
└─[0] <git:(argo 57060c1✱) > k get secret -n argocd argocd-repo-github-podinfo  -oyaml  
apiVersion: v1
data:
  name: cG9kaW5mbw==
  password: ""
  url: aHR0cHM6Ly9naXRodWIuY29tL3N0ZWZhbnByb2Rhbi9wb2RpbmZvLmdpdA==
  username: ""
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: argocd-baseline
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2023-08-03T12:01:33Z"
  labels:
    app.kubernetes.io/instance: argocd-baseline
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.7.7
    argocd.argoproj.io/secret-type: repository
    helm.sh/chart: argo-cd-5.38.1
  name: argocd-repo-github-podinfo
  namespace: argocd
  resourceVersion: "2721"
  uid: 0bc24a4c-6b3b-49c3-98d6-85461942d03e
type: Opaque
```

When debugging I see this error which results in failing to watch this secret

```bash
[info]  9b60fe92-e214-4673-8afe-bdcd0145f827 argocd/argocd-repo-github-podinfo       Mutate request: /v1/Secret
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null
    at new NodeError (node:internal/errors:405:5)
    at Function.from (node:buffer:333:9)
    at base64Decode (/Users/cmwylie19/pepr-zarf-agent/node_modules/pepr/dist/lib.js:986:17)
    at convertFromBase64Map (/Users/cmwylie19/pepr-zarf-agent/node_modules/pepr/dist/lib.js:975:21)
    at processor (/Users/cmwylie19/pepr-zarf-agent/node_modules/pepr/dist/lib.js:1004:18)
    at mutate (/Users/cmwylie19/pepr-zarf-agent/node_modules/pepr/dist/lib.js:1146:30)
    at Layer.handle [as handle_request] (/Users/cmwylie19/pepr-zarf-agent/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/cmwylie19/pepr-zarf-agent/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/cmwylie19/pepr-zarf-agent/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/cmwylie19/pepr-zarf-agent/node_modules/express/lib/router/layer.js:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
[2023-08-03T12:01:33.370Z] POST /mutate?timeout=30s [500] 3 
```

Despite having a code in place to do so:

```javascript
When(a.Secret)
  .IsCreatedOrUpdated()
  .InNamespace("argocd")
  // .WithLabel("argocd.argoproj.io/secret-type","repository")
  .Then(secret => {
     Log.info("argocd-repo-github-podinfo ",secret.Raw?.metadata?.name)
    if (argoSecretLabels(secret)){
      try {

        secret.Raw = JSON.parse(
          _transformer.transformArgoSecret(
            secret.Raw,
            secret.Request,
            _initSecrets.zarfStateSecret.gitServer.address,
            _initSecrets.zarfStateSecret.gitServer.pushUsername,
            _initSecrets.zarfStateSecret.gitServer.pullPassword,
            _initSecrets.zarfStateSecret.gitServer.pullUsername

          )
        )
        console.log("secret", JSON.stringify(secret.Raw, undefined, 2));
      } catch (err) {
        Log.error("Error transforming argo secret", err)
      }
    }
  })
  ```
  
  What is the recommended work around for this? Should I handle this secret outside of Pepr for now?

**Comment by cmwylie19** [comment]
I have a PR to fix this. Submitting soon
