### ISSUE TITLE
Pepr always fails when you select "audit" or "reject" when creating a new capability

### ISSUE THREAD

**Issue by AustinAbro321** [defenseunicorns/pepr#235]
There are inconsistent values between the askErrorBehavior prompt and what's looked for when pepr validates. Gives an error like below when you run `npx pepr dev`

```
Running module /home/austin/code/test-4/dist/pepr-d26d73ab-fb93-5747-9085-b4e29dc96f23.js
/home/austin/code/test-4/node_modules/pepr/dist/lib.js:1485
      throw new Error(`Invalid onErrors value: ${config.onError}`);
      ^

Error: Invalid onErrors value: audit
    at new PeprModule (/home/austin/code/test-4/node_modules/pepr/dist/lib.js:1485:13)
    at Object.<anonymous> (/home/austin/code/test-4/dist/pepr-d26d73ab-fb93-5747-9085-b4e29dc96f23.js:146:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.5.1
```

https://github.com/defenseunicorns/pepr/blob/076ba735a7ada88b07a9655ab90675bde02c73c6/src/cli/init/walkthrough.ts#L36-L60

https://github.com/defenseunicorns/pepr/blob/076ba735a7ada88b07a9655ab90675bde02c73c6/src/lib/module.ts#L41-L44

**Comment by bdw617** [comment]
@AustinAbro321 it's not a difficult fix, but going to let @jeff-mccoy own it as he understands this specific problem well.
