### ISSUE TITLE
Potential Regression around `npx pepr monitor`

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#815]
### Environment

It was reported that there is a potential bug around `npx pepr monitor`.

node v18 and v22

Run `npx pepr monitor` when you have the webhooks deployed

```bash
ApiException [Error]: HTTP-Code: Error: HTTP-Code: 400
Message: Error occurred in log request
Body: undefined
Headers: {"audit-id":"dc2c9ff4-f3d1-4e98-846f-19ab85105897","cache-control":"no-cache, private","connection":"close","content-length":"262","content-type":"application/json","date":"Mon, 20 May 2024 16:01:16 GMT"}
Message: Error occurred in log request
Body: undefined
Headers: {"code":400,"headers":{"audit-id":"dc2c9ff4-f3d1-4e98-846f-19ab85105897","cache-control":"no-cache, private","connection":"close","content-length":"262","content-type":"application/json","date":"Mon, 20 May 2024 16:01:16 GMT"}}
    at /Users/cmwylie19/pepr/pepr-test-module/node_modules/@kubernetes/client-node/dist/log.js:71:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Log.log (/Users/cmwylie19/pepr/pepr-test-module/node_modules/@kubernetes/client-node/dist/log.js:51:9)
    at async Command.<anonymous> (/Users/cmwylie19/pepr/pepr-test-module/node_modules/pepr/dist/cli.js:2470:7) {
  code: ApiException [Error]: HTTP-Code: 400
  Message: Error occurred in log request
  Body: undefined
  Headers: {"audit-id":"dc2c9ff4-f3d1-4e98-846f-19ab85105897","cache-control":"no-cache, private","connection":"close","content-length":"262","content-type":"application/json","date":"Mon, 20 May 2024 16:01:16 GMT"}
      at /Users/cmwylie19/pepr/pepr-test-module/node_modules/@kubernetes/client-node/dist/log.js:67:23
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Log.log (/Users/cmwylie19/pepr/pepr-test-module/node_modules/@kubernetes/client-node/dist/log.js:51:9)
      at async Command.<anonymous> (/Users/cmwylie19/pepr/pepr-test-module/node_modules/pepr/dist/cli.js:2470:7) {
    code: 400,
    body: undefined,
    headers: {
      'audit-id': 'dc2c9ff4-f3d1-4e98-846f-19ab85105897',
      'cache-control': 'no-cache, private',
      connection: 'close',
      'content-length': '262',
      'content-type': 'application/json',
      date: 'Mon, 20 May 2024 16:01:16 GMT'
    }
  },
  body: undefined,
  headers: ApiException [Error]: HTTP-Code: 400
  Message: Error occurred in log request
  Body: undefined
  Headers: {"audit-id":"dc2c9ff4-f3d1-4e98-846f-19ab85105897","cache-control":"no-cache, private","connection":"close","content-length":"262","content-type":"application/json","date":"Mon, 20 May 2024 16:01:16 GMT"}
      at /Users/cmwylie19/pepr/pepr-test-module/node_modules/@kubernetes/client-node/dist/log.js:67:23
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Log.log (/Users/cmwylie19/pepr/pepr-test-module/node_modules/@kubernetes/client-node/dist/log.js:51:9)
      at async Command.<anonymous> (/Users/cmwylie19/pepr/pepr-test-module/node_modules/pepr/dist/cli.js:2470:7) {
    code: 400,
    body: undefined,
    headers: {
      'audit-id': 'dc2c9ff4-f3d1-4e98-846f-19ab85105897',
      'cache-control': 'no-cache, private',
      connection: 'close',
      'content-length': '262',
      'content-type': 'application/json',
      date: 'Mon, 20 May 2024 16:01:16 GMT'
    }
  }
}
```

**Comment by cmwylie19** [comment]
Unable to reproduce bug on the main branch. This seems to be environmental. The reporter of the bug also cleared the cluster and it did not occur again.
